apiVersion: v1
kind: ConfigMap
metadata:
  name: proyecto-config
  namespace: proyecto-1036622
data:
  mongo-db: proyecto_db
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: proyecto-1036622
type: Opaque
stringData:
  username: usuario_mongo
  password: cambiar_esta_password
  uri: mongodb://usuario_mongo:cambiar_esta_password@mongo:27017/proyecto_db?authSource=admin
